spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQANF6uA1gN/gnUJ6yBN/SAsuuWY2xcL3/jsZ7srKsaKGgAAuyCMpNPJe6Zq0nzp+zmAyClsmmDKeBkEm6NjpkW5vvITQUD9jbwIcsOJDMMzFdNYBEuuZEqx8h2BhV/LPvoqDzV3L2fk8zUolp/2gl+ZvBQeHWZPj3CTE9pJzaUfaqL6M4q9ULr8IW6q3E6KuWj4sPW5BUQ0B/ozqR6tgYuZncMngN21bx3eyfPMAxm/8SDqHU00Tfewv8hkHkxVCadITi959SgfXK8Ot07PVDn2dxlKwX51SFaU5d0MKZMPnhn7BzumvIfb32jJ+gzuoMSjsfpdS5yl4l1UxMqraYVks5MTDrftNtqAQctfZFRFalD/vDzYjOqHwVHBQwwkCwo='